# -*- coding: utf-8 -*-
"""01_pytorch_workflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VKIWnLuRW2hebC2Nf-gO0TlMH56iFBi6
"""

import matplotlib.pyplot as plt
import numpy as np
import torch
from torch import nn
import math

# Create *known* parameters
weight  = 0.8
bias = 0.2

# Create
start = 0
end = 1
step = 0.02
X = torch.arange(start, end, step).unsqueeze(dim=1)
y = weight * X + bias
X[:10], y[:10] # pyright: ignore[reportUnusedExpression]

# min = 0
# max = 100
# step = 10
# array = np.arange(min, max, step)
# print(array + 10)

def plot_predictions(train_data, # type: ignore
                     train_labels,
                     test_data,
                     test_labels,
                     predictions=None):
  """
  Plots training data, test data and compares predictions.
  """
  plt.figure(figsize=(10, 7))

  # Plot training data in blue
  plt.scatter(train_data, train_labels, c="b", s=4, label="Training data")

  # Plot test data in green
  plt.scatter(test_data, test_labels, c="g", s=4, label="Testing data")

  if predictions is not None:
    # Plot the predictions in red (predictions were made on the test data)
    plt.scatter(test_data, predictions, c="r", s=4, label="Predictions")

  # Show the legend
  plt.legend(prop={"size": 14})



"""Machine learning is a game of two parts:

Turn your data, whatever it is, into numbers (a representation).
Pick or build a model to learn the representation as best as possible.
Sometimes one and two can be done at the same time.

But what if you don't have data?

Well, that's where we're at now.

No data.

But we can create some.

Let's create our data as a straight line.

We'll use linear regression to create the data with known parameters (things that can be learned by a model) and then we'll use PyTorch to see if we can build model to estimate these parameters using gradient descent.

Don't worry if the terms above don't mean much now, we'll see them in action and I'll put extra resources below where you can learn more.

https://en.wikipedia.org/wiki/Gradient_descent

Split data into training and test sets
We've got some data.

But before we build a model we need to split it up.

One of most important steps in a machine learning project is creating a training and test set (and when required, a validation set).

Each split of the dataset serves a specific purpose:

Split	Purpose	Amount of total data	How often is it used?
Training set	The model learns from this data (like the course materials you study during the semester).	~60-80%	Always
Validation set	The model gets tuned on this data (like the practice exam you take before the final exam).	~10-20%	Often but not always
Testing set	The model gets evaluated on this data to test what it has learned (like the final exam you take at the end of the semester).	~10-20%	Always
For now, we'll just use a training and test set, this means we'll have a dataset for our model to learn on as well as be evaluated on.

We can create them by splitting our X and y tensors.

Note: When dealing with real-world data, this step is typically done right at the start of a project (the test set should always be kept separate from all other data). We want our model to learn from training data and then evaluate it on test data to get an indication of how well it generalizes to unseen examples.
"""

len(X), len(y) # type: ignore

train_split = int(0.8 * len(X))
X_train, y_train = X[:train_split], y[:train_split]
x_test, y_test  = X[train_split:], y[train_split:]
len(X_train), len(y_train), len(x_test), len(y_test) # pyright: ignore[reportUnusedExpression]

# import matplotlib.pyplot as plt
# plt.scatter(X_train, y_train, c="r", label = "Training data")
# plt.scatter(x_test, y_test, c="b", label = "Testing data")
# plt.legend

# from sklearn.model_selection import train_test_split
# from sklearn.linear_model import LinearRegression
# lm = LinearRegression()
# lm.fit(X_train, y_train)
# test_x = lm.predict(x_test)
# test_x

class LinearRegressionModel(nn.Module):
  # Almost everything in pytorch inherits from nn.module
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(1, requires_grad=True, dtype= torch.float))
    self.bias = nn.Parameter(torch.randn(1, requires_grad =True, dtype=torch.float))

  def forward(self, x:torch.Tensor) -> torch.Tensor:
    return self.weights * x + self.bias

"""Recommendation: Watch Backpropogation and gradient descent, pure fun physics. 3blue1brown.

Subclass nn.Module => contains all the building blocks for neural networks
Initialise model parameter => used in varios competations.
requires_grad = true => Pytorch will track the gradient function, the vector partial derivative.

def(forward) => any subclass of nn.module needs to override forward(). This defines  the computation model
"""

# Pytorch model
torch.manual_seed(42)
# Create an instance of model (this is a subclass of nn.module)
model_0 = LinearRegressionModel()
list(model_0.parameters())

"""torch.nn - contains all of the builfing for computational graphs
torch.nn.Paramter - what parameters should our model try and learn
Module, the base network modules
"""

# List named parameters
weight, bias # pyright: ignore[reportUnusedExpression] # pyright: ignore[reportUnusedExpression]

model_0.state_dict()
# This is the prediction of the model. We are going to feed more data until it get's the weight and bias correct.

# To check models predicitive power, let's see how well it predicts y_test given x_test
# from sklearn.linear_model import LinearRegression
# lm = LinearRegression()
# lm.fit(x_test, y_test)
# test_predictions = lm.predict(x_test) # type: ignore

# plt.scatter(x_test, y_test, c="b", label="Testing data")
# plt.plot(x_test, test_predictions, c="g", label="Linear Regression predictions")
# plt.legend()
# plt.show()

# WOhooo, perfect, it can predict it perfectly. Let's do the same using our class and pytorch.

# Making predictions with our model
with torch.inference_mode():
  y_preds = model_0(x_test)
y_preds # pyright: ignore[reportUnusedExpression]

y_test # pyright: ignore[reportUnusedExpression]



def plot_predictions(train_data, train_labels, test_data, test_labels, predictions=None):
  """
  Plots training data, test data and compares predictions.
  """
  plt.figure(figsize=(10, 7))

  # Plot training data in blue
  plt.scatter(train_data, train_labels, c="r", s=4, label="Training data")

  # Plot test data in green
  plt.scatter(test_data, test_labels, c="b", s=4, label="Testing data")

  # Are there predictions?
  if predictions is not None:
    # Plot the predictions in red (predictions were made on the test data)
    plt.scatter(test_data, predictions, c="g", s=4, label="Predictions")

  # Show the legend
  plt.legend(prop={"size": 14})
  plt.show()



plot_predictions(train_data=X_train, train_labels=y_train, test_data=x_test, test_labels=y_test, predictions=y_preds)



"""As we can see, the predictions are no where near reailty, even though the pattern is extremley straight forward.
This is is because they start from unknown or paramater and slowly shift to known parameters through checking the consistancy of the results.
There is a loss function to track the error. The optimizer, takes the loss function into consideration and tweaks the prediction till we have a perfect prediction.

"""

list(model_0.parameters())

# We need a training loop and a testing loop. By lowering the loss function every time, we would get the red dots near the green dots.

# Setting up a loss function:
loss_fn = nn.L1Loss()

# Set up an optimizer
optimizer = torch.optim.SGD(params=model_0.parameters(), lr=0.01)
# lr = learning rate, super important. Can be seen as arange/ how big a step.



# An epoch is the one loop through the data
torch.manual_seed(42)
epochs = 250

epoch_count = []
loss_values = []
test_loss_values = []

#0. Loop thorugh the data
for epoch in range(epochs):

  # Set the model to training mode:
  model_0.train()
  # => sets all param that require gradeint to False

  # 1. Forward pass
  y_pred = model_0(X_train)

  # 2. Calculate the loss
  loss = loss_fn(y_pred, y_train)
  # print(loss)


  # 3. Optimizer 0 grad
  optimizer.zero_grad()

  # 4. Perform backpropagation on the loss with respect to param of the model
  loss.backward()

  # 5. Step the optimizer (perform gradient descent)
  optimizer.step()
  # by default how the optimiser changes will accumulate through the loop so.. we have to 0 them above in step 3

  model_0.eval()
  # print(model_0.state_dict() )
  with torch.inference_mode():
    test_pred = model_0(x_test)
    test_loss = loss_fn(test_pred, y_test)
    # print(f"Epoch: {epoch} | test_loss: {test_loss}")

  # Append to loss lists
  epoch_count.append(epoch)
  loss_values.append(loss.detach().numpy())
  test_loss_values.append(test_loss.detach().numpy())

torch.manual_seed(42)
epochs = 250
for epoch in range(epochs):
  y_pred = model_0(X_train)
  loss = loss_fn(y_pred, y_train)
  print(loss)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  model_0.eval()
  print(model_0.state_dict() )

  # Testing
  model_0.eval()
  with torch.inference_mode():
    test_pred = model_0(x_test)
    test_loss = loss_fn(test_pred, y_test)
    print(f"Epoch: {epoch} | test_loss: {test_loss}")

# understanding what is happening.
# Epoch =  number of times the data is passed through the model
# Y-pred = model_0(X_train) => Pass the data through the model, this will perform the forward() method located within the model object.
# Loss function => calculate the loss value
# Zero the gradients = > quite technical, but they pretty much accumulate every epoch, we need a fresh start for the next epoch
# Perform Backpropagation => take the gradeients of the loss function, computes the grad of every para with requires_grad = True.

model_0.state_dict()

weight, bias # pyright: ignore[reportUnusedExpression]

with torch.inference_mode():
  y_preds_new = model_0(x_test)
  y_preds_new # pyright: ignore[reportUnusedExpression]


plot_predictions(train_data=X_train, train_labels=y_train, test_data=x_test, test_labels=y_test, predictions=y_preds_new)

# Plot the loss curves
plt.plot(epoch_count, loss_values, label="Train loss")
plt.plot(epoch_count, test_loss_values, label="Test loss")
plt.title("Training and test loss curves")
plt.ylabel("Loss")
plt.xlabel("Epochs")
plt.legend()

# Plot the loss curves
plt.plot(epoch_count, loss_values, label="Train loss")
plt.plot(epoch_count, test_loss_values, label="Test loss")
plt.title("Training and test loss curves")
plt.ylabel("Loss")
plt.xlabel("Epochs")
plt.legend()
plt.show()












